### ISSUE TITLE
would be a great resource with spaced repetition

### ISSUE THREAD

**Issue by cognominal** [woutdp/geoquest#1]
But for spaced repetition to work across browsers it would need a login system
I am learning svelte and wrote a login system. Needs to be updated to the new sveltekit though

https://e-student.org/spaced-repetition/
https://github.com/cognominal/authy

**Comment by woutdp** [comment]
Thanks you for creating an issue. 

I'd prefer to not have a login system to keep things simple, both for user and for me.
It is possible to save state in localstorage, and to even create an export import system to work across browsers.
Maybe something to look into

**Comment by woutdp** [comment]
Thanks for the issue but, closing for now as it doesn't describe a specific feature, feel free to reopen new issues with specific feature requests
