### ISSUE TITLE
The color of a country should change over games

### ISSUE THREAD

**Issue by cognominal** [woutdp/geoquest#2]
I noticed that color helps me to identify countries. But that is useless because it does not work outside of geoquest. 
I have a patch pending but so far it works only when reloading geoquest. 

A related limitation is there should be a choice of colors for diffrent types of color blindness.

**Comment by woutdp** [comment]
Feel free to make a PR once it's working without reloading geoquest, I'd be happy to merge :)

**Comment by woutdp** [comment]
Added by @cognominal https://github.com/woutdp/geoquest/commit/00985b696d57983bffac47061a6b9fa5d15df82d
