### ISSUE TITLE
Turn the game into a Progressive Web App (PWA)

### ISSUE THREAD

**Issue by youssefmagdyy** [woutdp/geoquest#6]
I really like playing the game on my phone and I think it would be great if it could be installed as a PWA for a cleaner, app-like experience.

Would it be okay if I worked on this and submitted a pull request?

Thanks!

**Comment by youssefmagdyy** [comment]
I don't know but I tried a couple of times on different devices and I can't manage to get it to install

**Comment by woutdp** [comment]
On android in chrome I do the following:
- Open `geoquest.gg` in chrome
- Go to settings and click `Add to Home screen`

I haven't tested out ios recently so if that's not working properly feel free to make a PR :)

**Comment by youssefmagdyy** [comment]
Yeah sorry my fault, now that i did as you said it works perfectly. I guess I’m just used to seeing the “Install as App” pop-up.

Thanks.
